### ISSUE TITLE
Формирование title в html документе динамически

### ISSUE THREAD

**Issue by ae-gladkikh** [laximoru/guayaquil_demo#1]
Приветствую. 

https://github.com/laximoru/guayaquil_demo/blob/995e4dc781d62585b661749abe8dc740cd4a9c70/com_guayaquil/layouts/index.twig#L18

Могли бы Вы сделать так, чтобы title в html формировался на основе каких-то данных, исходя из task={task}. 

Например если мы выбрали в дереве видов запчастей, фильтр воздушный, то и на странице в title должно быть что-то типа "Фильтр воздушный ABARTH CINQUECENTO ABARTH [NUOVA 500 ABARTH (2008-2012)]".

Спасибо.

**Comment by laximoru** [comment]
Вынес в свойство page_title  https://github.com/laximoru/guayaquil_demo/commit/fb7abff0a84ae2345df7da71dc9f13696b646065
